-- Portfolio Analyzer Database Schema
-- Generated by Competitive-Agents (Beta contribution)
-- SQLite database for portfolio management

-- Holdings table
CREATE TABLE IF NOT EXISTS holdings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL UNIQUE,
    shares REAL NOT NULL,
    avg_price REAL NOT NULL,
    current_price REAL,
    last_updated TEXT,
    market TEXT DEFAULT 'US',
    notes TEXT
);

-- Transactions table
CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    action TEXT NOT NULL CHECK(action IN ('buy', 'sell')),
    shares REAL NOT NULL,
    price REAL NOT NULL,
    date TEXT NOT NULL,
    fees REAL DEFAULT 0,
    notes TEXT
);

-- Score history table
CREATE TABLE IF NOT EXISTS score_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ticker TEXT NOT NULL,
    date TEXT NOT NULL,
    overall_score REAL NOT NULL,
    financial_score REAL,
    valuation_score REAL,
    momentum_score REAL,
    grade TEXT,
    UNIQUE(ticker, date)
);

-- Chat history table (for portfolio-chat skill)
CREATE TABLE IF NOT EXISTS chat_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    timestamp TEXT NOT NULL
);

-- Portfolio metadata
CREATE TABLE IF NOT EXISTS portfolio_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_holdings_ticker ON holdings(ticker);
CREATE INDEX IF NOT EXISTS idx_transactions_ticker ON transactions(ticker);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_score_history_ticker ON score_history(ticker);
CREATE INDEX IF NOT EXISTS idx_chat_history_session ON chat_history(session_id);

-- Initial metadata
INSERT OR IGNORE INTO portfolio_meta (key, value, updated_at)
VALUES ('version', '1.0.0', datetime('now'));

INSERT OR IGNORE INTO portfolio_meta (key, value, updated_at)
VALUES ('created_by', 'competitive-agents-fusion', datetime('now'));
