"""
Report Generation Module

Provides markdown report generation with Jinja2 templates.
"""

import logging
from pathlib import Path
from typing import Dict
from datetime import date

# Jinja2 for templates
try:
    from jinja2 import Environment, FileSystemLoader, Template
    JINJA2_AVAILABLE = True
except ImportError:
    JINJA2_AVAILABLE = False

logger = logging.getLogger(__name__)


class MarkdownReportGenerator:
    """Generate markdown reports using Jinja2 templates."""

    def __init__(self, template_path: Path):
        """Initialize generator with template path."""
        if not JINJA2_AVAILABLE:
            raise ImportError("Jinja2 not installed. Run: pip install jinja2")

        if not template_path.exists():
            logger.warning("Template not found: %s. Using default.", template_path)
            self.template = self._get_default_template()
        else:
            env = Environment(loader=FileSystemLoader(template_path.parent))
            self.template = env.get_template(template_path.name)

    def generate(self, data: Dict) -> str:
        """
        Generate markdown report from data.

        Args:
            data: {
                "jds": List[Dict],
                "matches": List[Dict],
                "ranked": List[Dict],
                "trends": Dict,
                "profile": Dict,
            }

        Returns:
            Markdown report string
        """
        # Prepare template context
        context = {
            "date": date.today().strftime("%Y-%m-%d"),
            "total_jds": len(data.get("jds", [])),
            "avg_score": data.get("trends", {}).get("avg_match_score", 0),
            "top_skills": data.get("trends", {}).get("top_skills", []),
            "skills_to_learn": data.get("trends", {}).get("skills_to_learn", []),
            "top_companies": data.get("ranked", [])[:10],
            "remote_stats": data.get("trends", {}).get("remote_stats", {}),
            "match_distribution": data.get("trends", {}).get("match_distribution", {}),
            "profile_name": data.get("profile", {}).get("personal", {}).get("name", "User"),
            "profile": data.get("profile", {}),  # Add full profile for template access
        }

        # Render template
        report = self.template.render(**context)

        return report

    def _get_default_template(self) -> Template:
        """Get minimal default template."""
        template_text = """# JD Analysis Report - {{ date }}

## Executive Summary

- **Total JDs Analyzed**: {{ total_jds }}
- **Average Match Score**: {{ avg_score }}%
- **Profile**: {{ profile_name }}

## 🎯 Actionable Insights

### Top 5 Skills to Learn

{% for skill, count, pct in skills_to_learn %}
{{ loop.index }}. **{{ skill }}** - Required in {{ count }} JDs ({{ pct }}%)
{% endfor %}

### Top 10 Companies to Apply

{% for match in top_companies %}
{{ loop.index }}. **{{ match.jd_company }}** - {{ match.score }}% match
   - Title: {{ match.jd_title }}
   - Remote: {{ "Yes" if match.jd_remote else "No" }}
   - Missing: {{ ", ".join(match.missing_skills[:5]) }}
   - URL: {{ match.jd_url or "N/A" }}
{% endfor %}

## 📊 Market Trends

### Top 20 Most Required Skills

| Rank | Skill | Frequency | Percentage |
|------|-------|-----------|------------|
{% for skill, count, pct in top_skills %}
| {{ loop.index }} | {{ skill }} | {{ count }} | {{ pct }}% |
{% endfor %}

### Remote Work Statistics

- **Fully Remote**: {{ remote_stats.remote_count }} ({{ remote_stats.remote_pct }}%)
- **On-site/Hybrid**: {{ remote_stats.onsite_count }} ({{ remote_stats.onsite_pct }}%)

### Match Score Distribution

{% for bucket, count in match_distribution.items() %}
- **{{ bucket }}**: {{ count }} JDs
{% endfor %}

## 📈 Next Steps

1. **Learn {{ skills_to_learn[0][0] if skills_to_learn else "identified skills" }}** - Highest ROI skill (needed in {{ skills_to_learn[0][1] if skills_to_learn else 0 }} JDs)
2. **Apply to {{ top_companies[0].jd_company if top_companies else "top companies" }}** - Best match ({{ top_companies[0].score if top_companies else 0 }}%)
3. **Focus on remote roles** - {{ remote_stats.remote_pct }}% of JDs offer remote work
4. **Build projects** showcasing top 3 missing skills
5. **Update resume** to highlight matched skills

---

*Generated by JD Analyzer v1.0.0*
"""

        return Template(template_text)
